[BE-166] fix: redis 대기열 및 1차 신청 수정
JNU-Parking-Ticket-Project/Parking-Ticket-BE pull request #344
Opened 2024-08-14 20:21 UTC by LJH098

## 주요 변경사항
1. EventIssuedEventHandler의 handle 메서드 수정
- DB Connection이 idle한 경우 redis 대기열에서 데이터 가져와서 그 데이터로 Registration 저장하게끔 수정
- DB Connection이 idle 한 경우 redis 대기열에서 pop을 하는게 아닌 데이터를 그냥 가져옴

2. 중복 신청 검증 로직 추가
- 1번에서 언급했듯이 redis 대기열에서 pop을 하는 것이 아닌 그냥 데이터를 가져 옴으로써 대기열에 신청 정보를 남겨두고 신청 시 redis에서 해당 신청 데이터가 있는지 확인 하는 검증이 추가 되었음.
   - 실제로 Registration을 save하는 로직이 이벤트 리스너(비동기) 부분에 있어서 DB에 Registration 데이터 존재 유무로만 중복 신청을 검증하는 것은 옳바르지 않음 (비동기로 save 하기전에 여러번 신청이 들어오면 그게 전부 save 될 수 도 있기 때문)

3. Redis 대기열(zset)의 key 분리
- 이전 상황은 "쿠폰 발급 저장소"라는 하나의 key로 대기열이 구축되어있어서 구간마다 옳바른 예비 번호를 부여할 수 없었기 때문에 key를 eventId와 구간 번호로 분리되게 수정했음
   - 예비 번호 를 zset의 zRank를 사용하여 (해당 key에 몇 번째 데이터인지 불러옴) 부여하고 있다.
   - eventId로도 분리한 이유는 이벤트 삭제할 때와 이벤트가 closed 될 때 해당 event에 해당 하는 redis 대기열을 삭제하고 싶어서 분리함
## 리뷰어에게...
대기열이 생각보다 문제가 많았었네요...
RedissonLock의 leaseTime은 따로 건들지 않아서 Swagger로 테스트 할 때 종종 attemp to lock unlock오류가 뜨던데 leaseTime을 수정해야될 것 같긴합니다.
## 관련 이슈

closes #343 

## 체크리스트

- [ ] `reviewers` 설정
- [ ] `label` 설정
- [ ] `milestone` 설정

2024-08-15 08:39 UTC, pyg410 commented on Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
> +    //    }
주석 삭제해주세여

2024-08-15 08:42 UTC, pyg410 commented on Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
> +            }
뭔가 이쪽 로직 잘못된거같아용

2024-08-15 08:45 UTC, pyg410 requested changes
신청 -> 유스케이스 -> 이벤트 발행 -> 큐에서 pop -> 해당 내용 저장

이렇게 하면, redis에서 pop하는 과정에서 익셉션이 터질 경우 해당 신청은 누락될 것 같슴다.

신청 -> 유스케이스 /분리/ 레디스 큐 size가 1이상인지 스캔 -> 1이상일 경우 pop -> 해당 내용 저장

이렇게 하는게 나을 것 같다는 생각입니당

2024-08-15 12:45 UTC, BlackBean99 reviewed
bless you

2024-08-15 12:45 UTC, BlackBean99 commented on Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
> +            String key = eventIssuedEvent.getEventId().toString() + "-" + sector.getSectorNumber();
Event에서 pop하는 거랑 redis pop 하는거랑 데이터를 confused 하게 usable 하게 되는 기존의 문제가 이어지고 있는 것 같아요.
결국 Redis 에서만 pop 한 데이터 1개만 only 하게 처리하고자 하지 않았나요?
지금 트리거가 Event인데 Redis 에서 쓰면 안될 것 같은데요?

2024-08-15 12:45 UTC, BlackBean99 commented on Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
> +            ChatMessage message = (ChatMessage) waitingQueueService.getValue(key);
getValue() 에서 Pre-null check하지 않나요? 별도로 아래 검사 안해도 될 것 같은데 내부 코드는 안까봄. 아님 말고 ㅋㅋㄹㅃㅃ

2024-08-15 12:45 UTC, BlackBean99 commented on Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Sector.java
> +    @JsonManagedReference(value = "sector-registration")
이거 Entity JSONManageReference 써서 Circular Reference 해결한 거 같은데 이거 PR Document에 write 해주세요

2024-08-15 12:45 UTC, BlackBean99 commented on Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/redis/RedisConfig.java
> +    }
JSONReference 때문에 Adapter 새로 넣으셨군요. Jackson2JsonRedisSerializer 잘 Message Handling 되는지 validate 해야할 것 같습니다. Stress Test 진행할 때 제가 한번 더 recheck하겠습니다.

2024-08-15 12:45 UTC, BlackBean99 commented on Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/redis/RedisRepository.java
> +        }
아래는 null check, isEmpty and Check 했는데 왜 위에서만 null-check 하나만 하나요. and 를 하던지 하나만 하던지 통일해야하지 않을까요? 기존 redis Template를 수정할만한 user request가 없을 것 같은데?

2024-08-23 09:45 UTC, pyg410 commented
if it works, it works👍

2024-08-23 09:46 UTC, pyg410 approved these changes

2024-08-23 12:32 UTC, BlackBean99 approved these changes
LGTM

2024-08-23 12:32 UTC, BlackBean99 commented on Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
> +                log.info("주차권 신청 저장 완료");
9월 신청 끝나면 로그 붙어 있는거 한번 다 지우죠. 이런거 쌓이면 메모리 차서 다 돈입니다 ㅎ

2024-08-23 12:32 UTC, BlackBean99 commented on Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
> +        AtomicInteger sectorCounter = counter.computeIfAbsent(sector, k -> new AtomicInteger(1));
Atomic Integer의 key값을 객체로 생성하게 될경우 동일한 객체를 키로 사용하면 상관없지만 동일하지 않고 동등한 객체를 key로 생성할 경우(즉 값은 같지만 다른 객체)인 경우 초기화하지 않나요? 파라미터로 받는 sector가 동일한 sector가 나온다고 보장할 수 있을까요?

2024-08-23 12:32 UTC, BlackBean99 commented on Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
> +        if (registrationAdaptor.existsByEmailAndIsSavedTrue(email, eventId)
IsSavedEqualsTrue 이런식으로 쓰는게 네이밍상 ㅋㅋ

2024-08-25 08:52 UTC, merged