[BE-170] feat: spring actuator thread pool endpoint 추가의 건
JNU-Parking-Ticket-Project/Parking-Ticket-BE pull request #351
Opened 2024-08-31 06:35 UTC by pyg410

## 주요 변경사항

- spring acutator thread pool endpoint 추가했슴다

## 리뷰어에게...

- 풀 사이즈, 엑티브 스레드 개수, 큐 사이즈, 코어풀 사이즈, 맥스풀 사이즈 넣었습니다.
- /actuator/threadpool 로 요청 날리면 됩니다

## 관련 이슈

closes #350 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [ ] `milestone` 설정

2024-08-31 13:36 UTC, LJH098 approved these changes
굿굿

2024-08-31 15:13 UTC, Kwon770 requested changes
application.yml에서 실제 허용하고 있는 actuator 경로에 threadpool이 없습니다. 하지만 추가한 경로인 metrics 안에는 굉장히 많은 매트릭 경로가 있어서, 추가한 커스텀 매트릭이 어떤 것인지 식별하기가 힘드네요. 

혹시 정상적으로 매트릭이 발생되었는지와 정확히 어떤 경로로 어떤 커스텀 매트릭을 획득할 수 있는지 확인가능할까요? prometheus로 스크랩필할려면 이런 부분이 명확해야 해서 부탁드립니다~

2024-09-01 05:28 UTC, pyg410 commented
> application.yml에서 실제 허용하고 있는 actuator 경로에 threadpool이 없습니다. 하지만 추가한 경로인 metrics 안에는 굉장히 많은 매트릭 경로가 있어서, 추가한 커스텀 매트릭이 어떤 것인지 식별하기가 힘드네요.
> 
> 혹시 정상적으로 매트릭이 발생되었는지와 정확히 어떤 경로로 어떤 커스텀 매트릭을 획득할 수 있는지 확인가능할까요? prometheus로 스크랩필할려면 이런 부분이 명확해야 해서 부탁드립니다~

`@Endpoint` 어노테이션의 id 속성이 threadpool의 endpoint 입니다.
커스텀 메트릭을 따로 설정해준 것이고, `@ReadOperation`어노테이션의 경우 Get 요청에 대한 Mapping처리를 하게 됩니다.

만약, `https://ip:8080/actuator`가 기본 actuator의 url이라면, `https://ip:8080/actuator/threadpool`로 접속하시면 다음과 같은 메트릭을 확인할 수 있습니다.

혹시 설명이 부족하다면 zep에서 같이 이야기 해보면 좋을 것 같네용

```
{
  "poolSize": 0,
  "activeCount": 0,
  "queueSize": 0,
  "corePoolSize": 8,
  "maxPoolSize": 2147483647
}
```

2024-09-01 08:00 UTC, Kwon770 approved these changes
잘되네요~ 수고하셨습니다!

2024-09-01 08:00 UTC, merged