[BE-174] 로그를 위한 인터셉터 추가
JNU-Parking-Ticket-Project/Parking-Ticket-BE pull request #363
Opened 2024-09-03 17:46 UTC by kssumin

## 주요 변경사항

## 리뷰어에게...

## 관련 이슈

closes #358 

## 체크리스트

- [ ] `reviewers` 설정
- [ ] `label` 설정
- [ ] `milestone` 설정

2024-09-03 18:14 UTC, kssumin commented on Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
잔여 여석이 남지 않았을 경우 로그를 다음과 같이 남기도록 했습니다!

2024-09-03 18:14 UTC, kssumin commented on Ticket-Api/src/main/java/com/jnu/ticketapi/config/CacheAccessRequestFilter.java
> +public class CacheAccessRequestFilter extends HttpServletRequestWrapper {
로깅 인터셉터에서 Http Request Body를 사용해야 하나

서블릿 Reqeust, Response는 단 한번만 읽을 수 있다는 제약사항이 있었습니다.
따라서 로깅 인터셉터에서 body를 읽어버리면 컨트롤러에서 body가 없어서 요청을 처리하지 못 하는 문제가 발생합니다.

따라서 로깅을 위해 Reqeust 객체를 여러 번 읽기 위한 Wrapper 클래스를 생성했습니다.

2024-09-03 18:19 UTC, kssumin commented on Ticket-Api/src/main/java/com/jnu/ticketapi/config/WebLogginInterceptor.java
> +        if (isSkipLogging(request)) {
swagger 로 요청이 들어오는 건 로그로 남길 필요성이 없을 것 같아 제외하였습니다.

2024-09-03 18:19 UTC, kssumin commented on Ticket-Api/src/main/java/com/jnu/ticketapi/config/ServletWrappingFilter.java
> +        filterChain.doFilter(wrapRequest, wrapResponse);
래핑된 요청과 응답 객체를 사용하여 필터 체인의 다음 필터를 호출합니다.

2024-09-03 23:49 UTC, Kwon770 requested changes
코드도 깔끔하고 설명까지, 정석같은 PR이네요 😀 다만 팔로우업되지 못한 사항이 있어, 필수 수정사항 2건, 수정요청사항 1건 있습니다. 간단한 사항들이 빠르게 확인부탁드려요~

2024-09-03 23:49 UTC, Kwon770 commented on Ticket-Api/src/main/java/com/jnu/ticketapi/config/WebConfig.java
> +        registry.addInterceptor(webLogginInterceptor);
오타 확인부탁드려요! Loggin > Logging

2024-09-03 23:49 UTC, Kwon770 commented on Ticket-Api/src/main/resources/application.yml
> +      - /api/swagger-ui.html
swagger 체크 잘 해주셨네요! 추가로 저희는 prometheus를 통해 actuator 지표를 2~5초마다 스크랩칭 중입니다. 따라서 actuator url도 no-logging pattern에서 제외 추가부탁드려요. 

actuator 하위 url이 여러 개이고 변경의 여지가 크므로, 다음과 같이 `/api/actuator/*` asterisk를 붙여 설정하는게 좋을 것 같습니다.

2024-09-03 23:49 UTC, Kwon770 commented on Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
> +            log.info("잔여 여석이 남지 않음. Registration: {}", registration);
추후 ELK를 통해 로그 관리를 할 확률이 높기 때문에, 로그 포멧을 정할때 1. 원하는 로그를 찾을때 사용할 수 있는 정규화된 prefix가 있고, 2. 로그 간의 일관성이 있으면 좋을 것 같습니다! 따라서

1. prefix로 사용하기에 한글은 적합하지 않은 것 같습니다.
2. 잘 추가해주신 주차권 신청 로그(`log.info("[registration request]" + getBody(request));`)와 일관성있게 작성되면 좋을 것 같습니다.

2024-09-04 03:36 UTC, kssumin commented on Ticket-Api/src/main/java/com/jnu/ticketapi/config/WebConfig.java
> +        registry.addInterceptor(webLogginInterceptor);
리뷰 반영했습니다! [fd2b1be](https://github.com/JNU-Parking-Ticket-Project/Parking-Ticket-BE/pull/363/commits/fd2b1befb2159f353d8a24df85ced00008ef4c7f)

2024-09-04 03:36 UTC, kssumin commented on Ticket-Api/src/main/resources/application.yml
> +      - /api/swagger-ui.html
리뷰 반영했습니다! [e887803](https://github.com/JNU-Parking-Ticket-Project/Parking-Ticket-BE/pull/363/commits/e8878032fdd5d256edfcbc4e545f86a407122578)

2024-09-04 03:36 UTC, kssumin commented on Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
> +            log.info("잔여 여석이 남지 않음. Registration: {}", registration);
리뷰 반영했습니다! [5598a52](https://github.com/JNU-Parking-Ticket-Project/Parking-Ticket-BE/pull/363/commits/5598a52b4de010b346494786c9498d42f118d728)

2024-09-04 03:40 UTC, kssumin commented on Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
> +            log.info("잔여 여석이 남지 않음. Registration: {}", registration);
리뷰 반영했습니다! [5a1f42f](https://github.com/JNU-Parking-Ticket-Project/Parking-Ticket-BE/pull/363/commits/5a1f42ff4b951eb40ae4406e0b3df00624704c72)

2024-09-04 04:33 UTC, LJH098 commented on Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
>          if (!registration.isSaved()) {
이렇게 하면 registration@1234 이런식으로 객체만 로깅되지 않나요?? (경험상 그랬던 것 같음)
regisration의 정보를 json형식처럼 한눈에 알아볼 수 있도록 하는게 좋을 것 같아요!
왜냐하면 중복되는 지원서가 있을 때 그 사람을 제외하고 여기 NoEventStockLeftException에 걸린 신청을 넣어야 하기 때문에 registration에 대한 정확한 정보가 필요합니다!

2024-09-04 04:39 UTC, kssumin commented on Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
>          if (!registration.isSaved()) {
제가 로컬 상에서 commit을  안 한 파일이 있었네요...감사합니다!

[ad2a66d](https://github.com/JNU-Parking-Ticket-Project/Parking-Ticket-BE/pull/363/commits/ad2a66dec16770e523ba23ce1750fb01b0b1b403)

Registration에 toString을 사용하여 객체의 주소값이 아니라 필드 값이 출력되도록 변경하였습니다.

2024-09-04 09:43 UTC, LJH098 approved these changes

2024-09-04 13:40 UTC, Kwon770 approved these changes
LGTM

2024-09-04 13:40 UTC, merged