[BE-182] feat: jacoco, sonarcloud 도입의 건
JNU-Parking-Ticket-Project/Parking-Ticket-BE pull request #377
Opened 2024-09-05 15:01 UTC by pyg410

## 주요 변경사항

- 소나클라우드, 자코코 스크립트 작성했습니다
- gradle의존성은 이미 있어서 따로 추가 안했습니다.
- github-script로 pr올리면 알아서 커멘트 달게 했습니다
- 슬랙 설정은 아직 안했습니다. 스크립트 최종본 나오면 연결시켜놓을게요

### 피드백 반영사항
- script 동작확인
- slack webhook(ci-checker 채널에 올림)
- PR 테스트커버리지 작성 완료
- sonarcloud organization key는 찾아보니, Owner인 서현이가 권한을 줘야 보이는 거라, 그냥 빼버렸습니다.(해결 완료)
- sonarcloud PR comment 적용완료
- slack에 sonarcloud quality gate 상태 요약 추가

![스크린샷 2024-09-22 오전 5 30 55](https://github.com/user-attachments/assets/33064c43-9cd3-440b-aec7-65570efe490e)
![스크린샷 2024-09-22 오전 5 32 00](https://github.com/user-attachments/assets/6cefc553-b845-48c2-bcc9-080bdfce3aae)

## 리뷰어에게...

- 스크립트 완성은 아니구,, 초안만 작성해둔 거라서 secret이나 slack같은거 따로 설정 안해놨습니다.
- ci 스크립트 간단하게만 해본건데.. 이렇게 구체적으로 요구사항 주면 머리아파요.. 피드백 받고 빨리 수정할거라 빨리빨리빨리빨리 리뷰해주세요(마감일이 너무 빡세요😞)

## 관련 이슈

closes #376 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [ ] `milestone` 설정

2024-09-06 23:24 UTC, LJH098 commented
쌈뽕하시네요 굿굿

2024-09-14 13:18 UTC, BlackBean99 reviewed
CI 짤때 어떤 목표로 플로우를 짰는지가 제일 중요합니다.
빌드 캐시하고 어떤 validation을 하는지 convention level은 어떻게 진행할지 이런 부분들을 고민해보면 어떨까요? 이미 spotless를 쓰고 있으니 spotless-check를 거는 것도 컨벤션 유지에 쉬운 방법이죠

2024-09-14 13:18 UTC, BlackBean99 commented on .github/workflows/code-covoerage.yaml
> +      - name: 테스트 커버리지 쳌
?? 췍췍

2024-09-14 13:18 UTC, BlackBean99 commented on .github/workflows/code-covoerage.yaml
> +            ${{ secrets.SLACK_WEBHOOK_URL }}
이렇게 직접 날리는 것보다 slack workflow있을텐데 그거 use 하시지..

2024-09-14 13:18 UTC, BlackBean99 commented on .github/workflows/code-covoerage.yaml
> +          echo "::set-output name=status::$STATUS"
이거 잠시 가동 중단시키는 거 어떻습니까 저희 아마 한동안 quality failed뜰텐데

2024-09-14 13:18 UTC, BlackBean99 commented on .github/workflows/code-covoerage.yaml
> +        run: ./gradlew clean build jacocoTestReport
빌드하기만 하고 push를 안하면 이미지 버리는거 아닌가요?

2024-09-14 13:18 UTC, BlackBean99 commented on .github/workflows/code-covoerage.yaml
> +          distribution: 'temurin'
왜 temurin쓰시나요? 무슨 근거로 이 자바 버전을 선택했는지 여쭤봐도 될까요? 다른 플로우도 이 jdk쓰고 있나요?

2024-09-14 13:18 UTC, BlackBean99 commented on .github/workflows/code-covoerage.yaml
> +          distribution: 'temurin'
추가적으로 CI 하게 될 경우 jre를 쓰지 않고 jdk를 써야하는 이유는 뭘까요?

2024-09-15 16:49 UTC, pyg410 commented on .github/workflows/code-covoerage.yaml
> +          distribution: 'temurin'
@BlackBean99 
타 jdk와 호환성이 좋아서 현재 배포 환경에서 무슨 jdk가 사용되고 있는지 모르는 상황에서 요거만큼 적절한 친구가 없다고 볼 수 있습니다.
나중에 jdk어떤거 쓰는지 알고나서는 바꿀 예정입니당
자바버전은 저희 프로젝트 환경이 17로 세팅되어 있으니깐 CI버전도 이걸로 했습니다.

그리고 역으로 궁금한게, JDK가 아닌 JRE로 세팅한다고 치면 빌드는 어떻게 해요? (진짜궁금) 방법이 있나요?
뭔가 방법이 있으니깐 물어보셨을거같아서요

2024-09-15 16:53 UTC, pyg410 commented on .github/workflows/code-covoerage.yaml
> +        run: ./gradlew clean build jacocoTestReport
왜냐하면 dev환경이 완벽하게 구축되어있지 않기 때문에 그부분은 일단 생략했습니다.

2024-09-15 16:54 UTC, pyg410 commented on .github/workflows/code-covoerage.yaml
> +          echo "::set-output name=status::$STATUS"
이부분도 상의해야겠네용
테스트커버리지는 걍 다 빼버리고 빌드되는지만 넣는게 나으려나

2024-09-15 16:55 UTC, pyg410 commented on .github/workflows/code-covoerage.yaml
> +            ${{ secrets.SLACK_WEBHOOK_URL }}
좋은 피드백 감사함다
이건 한번 찾아볼게용

2024-09-15 16:55 UTC, pyg410 commented on .github/workflows/code-covoerage.yaml
> +      - name: 테스트 커버리지 쳌
원투쓰리 췍췍

2024-09-29 08:17 UTC, Kwon770 requested changes
모두에게 영향을 미치는 CI PR이다보니, 확실히 하고 가겠습니다 ㅎㅎ. 확인부탁드려요.

2024-09-29 08:17 UTC, Kwon770 commented on build.gradle
>              // xml 위치 조정
테스트 통과하기 위한 Jacoco 커버리지 설정을 어떻게 하셨을까요? 아직 테스트코드가 작성되지 않은 상태이므로, 전체 프로젝트에 대한 커버리지 설정이 적용되어 있으면, PR들이 전부 failed로 기록될거에요. 전체 프로젝트 테스트 커버리지는 0으로 설정하고 신규로 생성된 PR의 테스트 커버리지는 70% 정도로 설정하면 좋을 것 같아요.

2024-09-29 08:17 UTC, Kwon770 commented on .github/workflows/code-covoerage.yaml
> +            ${{ secrets.SLACK_WEBHOOK_URL }}
요기 참고해서 적용 부탁드려요~

https://github.com/JNU-Parking-Ticket-Project/Parking-Ticket-BE/blob/main/.github/workflows/prod-deploy-v2-container.yaml#L98

2024-09-29 08:17 UTC, Kwon770 commented on .github/workflows/code-covoerage.yaml
> +        run: ./gradlew clean build jacocoTestReport
요건 어떤 내용일까요? dev 환경 이제 구축되어 있으니, 확인 부탁드려요~

2024-10-19 12:52 UTC, pyg410 commented on .github/workflows/code-covoerage.yaml
> +        run: ./gradlew clean build jacocoTestReport
이건 CD까지 생각하고 답변한거라 현재상황에서는 필요 없을듯합니다

2024-10-19 12:52 UTC, pyg410 commented on build.gradle
>              // xml 위치 조정
적용했슴다

2024-10-27 05:14 UTC, Kwon770 approved these changes
수정 내역 확인했습니다. LGTM

2024-10-27 05:18 UTC, LJH098 approved these changes

2024-10-27 10:19 UTC, merged