[BE-197] bug: ThreadPool 모니터링 개선
JNU-Parking-Ticket-Project/Parking-Ticket-BE pull request #405
Opened 2024-10-19 08:41 UTC by pyg410

## 주요 변경사항

Spring 기본적으로 사용하는 ThreadPool을 모니터링할 수 있게 수정했습니다.

## 리뷰어에게...

## 관련 이슈

closes #404 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [ ] `milestone` 설정

2024-10-20 01:20 UTC, Kwon770 requested changes
확인부탁드립니다..!

2024-10-20 01:20 UTC, Kwon770 commented on Ticket-Domain/src/main/resources/application-domain.yml
> -      initialize-schema: never # 스키마 자동 생성 비활성화 (한번만 수동으로 생성)
Quartz DDL 설정은 회의 때 잠깐 이야기나온 내용으로 기억해요. 이번 PR 무관한 내용이고, 수정되어서 안되는 부분입니다. 확인부탁드려요.

2024-10-20 01:20 UTC, Kwon770 commented on Ticket-Api/src/main/java/com/jnu/ticketapi/common/actuator/ThreadPoolConfig.java
> +    @Value("${thread.core-pool-size}")
Tomcat의 Threadpool과 Spring의 ThreadPool를 헷갈리신 것 같아요. 저희가 계속 이야기 나누었던 Threadpool은 DBCP대비 너무 많은 HTTP 요청을 받아내 데드락이 발생하지 않도록 한다는 맥락이였기 때문에, 여기서 나는 Threadpool은 HTTP 요청을 다루는 Thread를 말하는 것이였습니다. Spring의 WAS는 Tomcat이므로 Tomcat의 Threadpool에 대해 모니터링되어야 한다는 의미였습니다.

ThreadPoolTaskExecutor와 그와 연관된 클래스를 확인해보면, java.util.concurrent 패키지입니다. 즉, 자바 어플리케이션에서 비동기 작업을 하는데 사용되는 쓰레드들이고, 저희의 경우에는 Event나 @Async 어노테이션이 붙은 비동기 동작들에 사용됩니다.

따라서 Tomcat과 관련된 설정 및 모니터링에 대해 한번 더 파악부탁드립니다. 참고가 될만한 링크 첨부드려요!
https://expect.tistory.com/18

2024-10-20 03:14 UTC, pyg410 commented on Ticket-Api/src/main/java/com/jnu/ticketapi/common/actuator/ThreadPoolConfig.java
> +    @Value("${thread.core-pool-size}")
네 수정하겠습니다~

2024-10-27 05:17 UTC, Kwon770 approved these changes
수정 확인했습니다. 적용하고 개발서버에서도 테스트해보겠습니다~

2024-10-27 05:17 UTC, merged