[BE-198] feat: 공지사항 이미지 저장 및 조회
JNU-Parking-Ticket-Project/Parking-Ticket-BE pull request #413
Opened 2024-10-29 14:04 UTC by pyg410

## 주요 변경사항

- 공지사항 상세조회, 수정, 삭제 dto image list 필드 추가
- 공지사항 image Entity 추가 

## 리뷰어에게...

- Test예정. 아직 리뷰하지 마세요

## 관련 이슈

closes #407 

## 체크리스트

- [ ] `reviewers` 설정
- [x] `label` 설정
- [ ] `milestone` 설정

2024-11-14 03:57 UTC, LJH098 requested changes

2024-11-14 03:57 UTC, LJH098 commented on Ticket-Api/src/main/resources/application.yml
> +
applicaion-domain.yml에 logging 설정하는 곳이 있어서 거기다가 설정해주세요
```
org.springframework.cache: ${LOGGING_LEVEL:INFO}
org.ehcache: ${LOGGING_LEVEL:INFO}
javax.cache: ${LOGGING_LEVEL:INFO}
```

이렇게 하면 될듯

2024-11-14 03:57 UTC, LJH098 commented
굿굿 잘하셨네용!!

2024-11-14 12:17 UTC, pyg410 commented on Ticket-Api/src/main/resources/application.yml
> +
따흑흑 알겠습니다

2024-11-26 08:20 UTC, LJH098 approved these changes

2024-11-26 08:34 UTC, merged